
# Generated by CodiumAI
from pyeed.align.clustalo import ClustalOmega
from pytest_mock import mocker


import pytest

class TestClustalOmega:

    # ClustalOmega aligns multiple sequences and returns the alignment result.
    def test_align_multiple_sequences(self):
        # Arrange
        sequences = ["ATCG", "GCTA", "TTAA"]
        clustal_omega = ClustalOmega()
    
        # Act
        alignment = clustal_omega.align(sequences)
    
        # Assert
        assert isinstance(alignment, MultipleSeqAlignment)
        assert len(alignment) == len(sequences)

    # ClustalOmega fails to get the image from Docker Hub.
    def test_fail_to_get_image_from_docker_hub(self):
        # Arrange
        clustal_omega = ClustalOmega()
        clustal_omega._client.images.get.side_effect = docker.errors.ImageNotFound
    
        # Act and Assert
        with pytest.raises(Exception):
            clustal_omega.run_container(command="", data=[])