# Generated by CodiumAI
"""
from pyeed.core.alignment import Alignment
from pyeed.align.hmm import HMM


import pytest

class TestHMM:

    # HMM can be initialized with a name and an Alignment object
    def test_initialized_with_name_and_alignment(self):
        alignment = Alignment()
        alignment.add_to_input_sequences(id="seq1", sequence="ATCG")
        alignment.add_to_input_sequences(id="seq2", sequence="GCTA")

        hmm = HMM(name="test_hmm", alignment=alignment)

        assert hmm.name == "test_hmm"
        assert hmm.alignment == alignment
        assert hmm.model is None

"""
