# Generated by CodiumAI
import logging

from pyeed.core.dnarecord import DNARecord
from pyeed.core.organism import Organism

LOGGER = logging.getLogger(__name__)


class TestDNARecord:
    # In Docs
    def test_instantiation_from_ncbi(self):
        dna_record = DNARecord.get_id("AF397067.1")

        LOGGER.info(f"DNA Record: {dna_record}")

        assert dna_record is not None

    def test_instantiation_from_ncbi_list(self):
        dna_records = DNARecord.get_ids(["AF397067.1", "AF397068.1"])

        LOGGER.info(f"DNA Records: {dna_records}")

        assert dna_records is not None

    def test_fields(self):
        dna_record = DNARecord(
            name="Test",
            id="AA",
            sequence="ATCG",
            organism=Organism(name="Test", taxonomy_id="1"),
        )

        assert dna_record.id == "AA"
        assert dna_record.name == "Test"
        assert dna_record.sequence == "ATCG"
        assert dna_record.organism.name == "Test"
        assert dna_record.organism.taxonomy_id == 1
