# Generated by CodiumAI
import pytest

from pyeed.core.organism import Organism
from pyeed.core.proteininfo import ProteinInfo
from pyeed.core.proteinregiontype import ProteinRegionType
from pyeed.core.proteinsitetype import ProteinSiteType
from pyeed.core.span import Span


class TestProteinInfo:

    # In Docs
    def test_instantiation_from_ncbi(self):
        protein_info = ProteinInfo.get_id("UCS38941.1")

    # create a ProteinInfo object with all required fields
    def test_create_protein_info_with_required_fields(self):
        protein_info = ProteinInfo(
            name="MyProtein",
            source_id="ABC123",
            sequence="MVKLQWERTY",
            organism=Organism(
                name="Homo sapiens",
                taxonomy_id="tax12345",
                domain="Eukaryota",
                kingdom="Animalia",
                phylum="Chordata",
                tax_class="Mammalia",
                order="Primates",
                family="Hominidae",
                genus="Homo",
                species="sapiens",
            ),
        )

        assert protein_info.name == "MyProtein"
        assert protein_info.source_id == "ABC123"
        assert protein_info.sequence == "MVKLQWERTY"
        assert protein_info.organism.name == "Homo sapiens"
        assert protein_info.organism.taxonomy_id == "tax12345"
        assert protein_info.organism.domain == "Eukaryota"
        assert protein_info.organism.kingdom == "Animalia"
        assert protein_info.organism.phylum == "Chordata"
        assert protein_info.organism.tax_class == "Mammalia"
        assert protein_info.organism.order == "Primates"
        assert protein_info.organism.family == "Hominidae"
        assert protein_info.organism.genus == "Homo"
        assert protein_info.organism.species == "sapiens"

    # add a region to ProteinInfo object
    def test_add_region_to_protein_info(self):
        protein_info = ProteinInfo(
            name="MyProtein",
            source_id="ABC123",
            sequence="MVKLQWERTY",
            organism=Organism(
                name="Homo sapiens",
                taxonomy_id="tax12345",
                domain="Eukaryota",
                kingdom="Animalia",
                phylum="Chordata",
                tax_class="Mammalia",
                order="Primates",
                family="Hominidae",
                genus="Homo",
                species="sapiens",
            ),
        )

        region = protein_info.add_to_regions(
            type=ProteinRegionType.DOMAIN.value,
            name="Domain1",
            spans=[Span(start=1, end=10, id="span1")],
        )

        assert len(protein_info.regions) == 1
        assert protein_info.regions[0] == region
        assert protein_info.regions[0].type == ProteinRegionType.DOMAIN.value
        assert protein_info.regions[0].name == "Domain1"
        assert protein_info.regions[0].spans == [Span(start=1, end=10, id="span1")]

    # add a site to ProteinInfo object
    def test_add_site_to_protein_info(self):
        protein_info = ProteinInfo(
            name="MyProtein",
            source_id="ABC123",
            sequence="MVKLQWERTY",
            organism=Organism(
                name="Homo sapiens",
                taxonomy_id="tax12345",
                domain="Eukaryota",
                kingdom="Animalia",
                phylum="Chordata",
                tax_class="Mammalia",
                order="Primates",
                family="Hominidae",
                genus="Homo",
                species="sapiens",
            ),
        )

        site = protein_info.add_to_sites(
            name="Site1",
            type=ProteinSiteType.ACTIVE.value,
            positions=[1, 2, 3],
        )

        assert len(protein_info.sites) == 1
        assert protein_info.sites[0] == site
        assert protein_info.sites[0].name == "Site1"
        assert protein_info.sites[0].type == ProteinSiteType.ACTIVE.value
        assert protein_info.sites[0].positions == [1, 2, 3]
