# Generated by CodiumAI
from pyeed.core.organism import Organism
from pyeed.core.dnarecord import DNARecord

import logging

LOGGER = logging.getLogger(__name__)

class TestDNARecord:

    # In Docs
    def test_instantiation_from_ncbi(self):
        dna_record = DNARecord.get_id('AF397067.1')

        LOGGER.info(f"DNA Record: {dna_record}")

        assert dna_record is not None

