site_name: PyEED Documentation
repo_url: https://github.com/PyEED/pyeed/
repo_name: PyEED/pyeed
site_url: https://pyeed.github.io/pyeed/
site_author: Max Häußler


nav:
  - 🏠 Home: index.md
  - ⚡️ Quick Start:
    - quick_start/index.md
    - The Sequence objects: quick_start/basics.md
    - Finding Sequences: quick_start/blast.md
    - Aligning Sequences: quick_start/alignments.md
    - Clustering Sequences: quick_start/clustering.md
    - Creating Sequence Networks: quick_start/networks.md
  - 🔎 Examples:
    - Create a sequence network: usecases/usecase1.md
  - ⬇️ Installation:
    - via PIP: installation/via_pip.md
    - Docker: installation/docker.md
    - JupyterLab with PyEED: installation/jupyterlab.md
    # - Local BLAST: installation/setup_local_blast.md


theme:
  name: material
  logo: figs/pyeed.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.indexes
    - navigation.footer

    - content.action.view
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.links
    - content.code.select
    - content.code.copy
    - content.code.annotation
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true