[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyeed"
version = "1.0.0"
description = "Toolkit to create, annotate, and analyze sequence data"
authors = [
  { name = "Max Häußler", email = "max.haeussler@gmail.com" }
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.123.0",
    "fastmcp>=2.13.3",
    "httpx>=0.28.1",
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.7",
    "loguru>=0.7.3",
    "matplotlib>=3.10.7",
    "mcp[cli]>=1.22.0",
    "neo4j>=5.28.2",
    "pydantic>=2.11.7",
    "pymilvus>=2.6.3",
    "python-dotenv>=1.1.1",
    "rdkit>=2025.9.1",
    "rich>=14.1.0",
    "scikit-bio>=0.7.1.post1",
    "selfies>=2.2.0",
    "strawberry-graphql[asgi,cli]==0.287.0",
    "tenacity>=9.1.2",
    "toon-format",
    "torch>=2.8.0",
    "transformers>=4.48.1",
    "uvicorn[standard]>=0.38.0",
]

[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
warn_return_any = true
check_untyped_defs = true
strict = true

[tool.ruff]
line-length = 100
target-version = "py313"

[tool.ruff.lint]
select = ["E","F","W","I","UP","B","SIM","PL","RUF"]
ignore = ["E203"]

[tool.ruff.lint.pylint]
max-args = 100
max-statements = 100

[tool.ruff.format]

[tool.uv.sources]
toon-format = { git = "https://github.com/toon-format/toon-python.git" }

[dependency-groups]
dev = [
    "pytest>=9.0.0",
    "pytest-asyncio>=0.25.2",
    "pytest-sugar>=1.1.1",
    "ruff>=0.12.12",
    "ruff-lsp>=0.0.62",
    "zensical>=0.0.11",
]
