[tool.poetry]
name = "pyeed"
version = "0.1.0"
description = "Enzyme engineering toolkit"
authors = ["haeussma <83341109+haeussma@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
biopython = "^1.81"
sdrdm_database = "^0.2.0"
tqdm = "^4.66.1"
sdrdm = {git = "https://github.com/JR-1991/software-driven-rdm.git", rev = "linking-refactor"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
