[tool.poetry]
name = "pyeed"
version = "0.1.0"
description = "python enzyme engineering toolkit"
authors = ["haeussma <83341109+haeussma@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
pydantic = "1.10"
biopython = "^1.81"
numpy = "^1.26.0"
sdrdm = {git = "https://github.com/JR-1991/software-driven-rdm.git", rev = "linking-refactor"}
sdrdm-database = {git = "https://github.com/JR-1991/sdrdm-database.git"}
tqdm = "^4.66.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
