[tool.poetry]
name = "pyeed"
version = "0.1.2"
description = "Enzyme engineering toolkit"
authors = ["haeussma <83341109+haeussma@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "pyeed/core" },
    { include = "pyeed/fetchers" },
    { include = "pyeed/network" },
    { include = "pyeed/aligners" },
    { include = "pyeed/containers" },
    { include = "pyeed/utility" },
]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
biopython = "^1.81"
tqdm = "^4.66.1"
sdrdm = {git = "https://github.com/JR-1991/software-driven-rdm.git", branch = "linking-refactor"}
sqlalchemy = "^2.0.22"
pymysql = "^1.1.0"
sdrdm-database = {version = "^0.4.1", extras = ["postgres"]}
psycopg2 = "^2.9.9"
networkx = "^3.2.1"
plotly = "^5.18.0"
nbformat = "^5.9.2"
scipy = "^1.11.3"
docker = "^7.0.0"
pyhmmer = "^0.10.11"
httpx = "^0.27.0"
nest-asyncio = "^1.6.0"
rich = "^13.0.0"
aiometer = "^0.5.0"

[tool.poetry.group.dev.dependencies]
mkdocs-material = "^9.5.9"
pytest = "^8.0.1"
python-dotenv = "^1.0.1"
pytest-mock = "^3.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
