[tool.poetry]
name = "pyeed"
version = "0.1.0"
description = "Enzyme engineering toolkit"
authors = ["haeussma <83341109+haeussma@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
biopython = "^1.81"
tqdm = "^4.66.1"
sdrdm = {git = "https://github.com/JR-1991/software-driven-rdm.git", branch = "linking-refactor"}
sdrdm-database = {extras = ["mysql"], version = "^0.3.0"}
sqlalchemy = "^2.0.22"
pymysql = "^1.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
