[tool.poetry]
name = "pyEED"
version = "0.1.0"
description = "Enzyme engineering toolkit"
authors = ["haeussma <83341109+haeussma@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "pyEED/core" },
    { include = "pyEED/ncbi" },
    { include = "pyEED/network" },
    { include = "pyEED/alignment" },
]

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
biopython = "^1.81"
tqdm = "^4.66.1"
sdrdm = {git = "https://github.com/JR-1991/software-driven-rdm.git", branch = "linking-refactor"}
sqlalchemy = "^2.0.22"
pymysql = "^1.1.0"
sdrdm-database = {version = "^0.4.1", extras = ["postgres"]}
psycopg2 = "^2.9.9"
networkx = "^3.2.1"
plotly = "^5.18.0"
nbformat = "^5.9.2"
scipy = "^1.11.3"
docker = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
