version: "2.2"
services:
  jupyter-lab:
    build:
      context: jupyterlab/
    image: haeussma/pyeed-notebook:latest
    container_name: jupyterlab
    ports:
      - '${JUPYTER_PORT}:${JUPYTER_PORT}'

  clustalo:
    build:
      context: clustalo/
    container_name: clustalo
    ports:
      - "5001:5001"
    volumes:
      - ./clustalo:/app/api
      - ./clustalo:/app/data
