# Use a base image
FROM ubuntu:latest

# Update the package list and install necessary packages
RUN apt-get update && apt-get install -y clustalo

# Set the default command to run when the container starts
CMD ["clustalo"]