name: Integration Tests (MySQL)

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2
          pip install -e .
      - name: Run example
        run: |
            cd ./examples
            python .github/scripts/example.py
            echo "Done"
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: 'db'
          MYSQL_USER: 'user'
          MYSQL_PASSWORD: 'user'
          MYSQL_ROOT_PASSWORD: 'root'
        ports:
          - '3306:3306'
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10